# Generated by Django 5.1.3 on 2024-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('acc_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
